### ISSUE TITLE
Need to assign tasks for remaining 2 phases

### ISSUE THREAD

**Issue by HelenG123** [CMPUT301F18T23/Symptomatic#10]
**TA's Feedback**
> Could be better organized in terms of priority. Might want to consider developing
an explicit priority system and assigning tasks within the 2 phases a rough level
of priority with respect to the end of that phase, so that what is required is agreed
upon and easily accessible by all team members during a sprint.

**Team Member to Address Problem**
> @N550 

**How to Address Problem** 
> Go through the release planning and explicit state the functionalities that each team member will work on for the remaining two phases of the project. Map the user story as well to the team member responsible for completing it.

**Comment by N550** [comment]
Each task is not delegated to specific team members.
