### ISSUE TITLE
Adding functional/integration testing to the release planning

### ISSUE THREAD

**Issue by HelenG123** [CMPUT301F18T23/Symptomatic#11]
**TA's Feedback**
> I also do not see any time dedicated to functional/integration testing. This should be included rather than done ad hoc

**Team Member to Address Problem**
> @N550 

**How to Address Problem** 
> Explicit state and delegate time to do functional/integration testing in the release planning.

**Comment by N550** [comment]
Functional and integration testing have both now been incorporated into both releases.
