### ISSUE TITLE
Separate test case for Caregiver

### ISSUE THREAD

**Issue by HelenG123** [CMPUT301F18T23/Symptomatic#22]
**TA's Feedback**
> There should be a separate test class for caregivers, in order to test the methods that are unique to that class.

**Team Member to Address Problem**
> @pineo 

**How to Address Problem** 
> Make a separate use case for Caregiver.

**Comment by N550** [comment]
Separate tests for caregivers is located within the user test class. These are tests that are only relevant to the caregivers.
