### ISSUE TITLE
Ensure that the Comment tests are checking the time, not the author

### ISSUE THREAD

**Issue by HelenG123** [CMPUT301F18T23/Symptomatic#24]
**TA's Feedback**
> The test timestamp in the comment tests appears to be checking the author rather than the time?

**Team Member to Address Problem**
> @N550 

**How to Address Problem** 
> Check the Comment tests to see if it's checking for either the author or time; make the appropriate changes.

**Comment by N550** [comment]
The issue has been resolved. It is not checking time.
