### ISSUE TITLE
No explicit mapping between user stories and use cases evident

### ISSUE THREAD

**Issue by HelenG123** [CMPUT301F18T23/Symptomatic#3]
**TA's Feedback**
> No explicit mapping between user stories and use cases evident

**Team Member Assigned to Resolve**
> @N550 

**How to Resolve**
> Point out to TA where the explicit mapping was in the Wiki.

**Comment by N550** [comment]
The uses cases and user stories are mapped out in the release plan.

**Comment by amy-xiang** [comment]
This was done during our last lab on Tuesday.
