### ISSUE TITLE
Add error checking and try catch for queries 

### ISSUE THREAD

**Issue by N550** [CMPUT301F18T23/Symptomatic#36]
**TA's Feedback**
> Some error checking and try catch for queries etc (though they appear to be stubs at the moment in some places. Make sure to implement by part 5 end)

**Team Member to Address Problem**
> @pineo @alr3 

**How to Address Problem** 
> Look through the code and find appropriate places to use error checking and try/catch.

**Comment by pineo** [comment]
Consistency checks are in place for user, problem, and record now. Upon creating any of the mentioned, it will first check the database to ensure integrity constraints, and reject the data should it not be consistent.
