### ISSUE TITLE
Clarify the relationships in the UML diagram. 

### ISSUE THREAD

**Issue by N550** [CMPUT301F18T23/Symptomatic#40]
**TA's Feedback**
> -However, as of right now most of the query logic/implementation seems to be handled by independent classes whose relationship to the others is not quite clear,
as it is absent from the UML diagram. They should be included, or documentation provided to clarify their relationship to the models/controllers

**Team Member to Address Problem**
> @HelenG123 @ahzam1 @amy-xiang @pineo @N550 @alr3 

**How to Address Problem** 
> Make the UML relationships more clear.

**Comment by HelenG123** [comment]
Added the independent classes to clarify the relationship to the models and controllers in the UML. Also, added additional notes to clarify where we're using the database/querying.
